export const SUBJECTS = Object.freeze([
  { code: "ENG", label: "English" },
  { code: "KISW", label: "Kiswahili" },
  { code: "MATH", label: "Mathematics" },
  { code: "SCI", label: "Integrated Science" },
  { code: "SST", label: "Social Studies" },
  { code: "CRE", label: "CRE" },
  { code: "IRE", label: "IRE" },
  { code: "HRE", label: "HRE" },
  { code: "COMP", label: "Computer Studies" },
  { code: "BUS", label: "Business Studies" },
  { code: "VART", label: "Visual Arts" },
  { code: "PARTS", label: "Performing Arts" },
  { code: "HOME", label: "Home Science" },
  { code: "HEALTH", label: "Health Education" },
  { code: "PE", label: "Sports and Physical Education" },
  { code: "AGRI", label: "Agriculture" },
  { code: "LANG", label: "Foreign Language" },
  { code: "SIGN", label: "Kenya Sign Language" },
]);