<script setup>
const clauses = [
  {
    title: "1. Acceptance of Terms",
    body: `By accessing, registering for, or using the Quantum Ripple School Management Platform, you agree to be bound by these Terms of Use.

If you do not agree to these terms, you must not access or use the platform.`
  },

  {
    title: "2. Eligibility",
    body: `The platform is intended for authorized educational institutions and their approved users.

Schools are responsible for ensuring that only authorized principals, administrators, teachers, parents, guardians and students access the platform according to their assigned permissions.`
  },

  {
    title: "3. User Accounts",
    body: `Users are responsible for:

• Maintaining accurate account information
• Keeping passwords confidential
• Using strong passwords
• Reporting unauthorized access immediately
• Protecting login credentials

Quantum Ripple may suspend accounts that pose security risks or violate these Terms.`
  },

  {
    title: "4. User Responsibilities",
    body: `Users agree not to:

• Violate applicable laws
• Share account credentials
• Upload malware or malicious software
• Attempt unauthorized access
• Reverse engineer the platform except where expressly permitted by law
• Circumvent platform security
• Scrape or copy platform data without authorization
• Manipulate academic, attendance or financial records without proper authorization
• Disrupt platform availability or integrity`
  },

  {
    title: "5. School Responsibilities",
    body: `Schools agree to:

• Obtain parental or guardian consent where required
• Ensure uploaded information is accurate
• Assign appropriate user permissions
• Protect administrator accounts
• Comply with applicable education and data protection laws
• Notify Quantum Ripple of suspected security incidents affecting the platform`
  },

  {
    title: "6. Intellectual Property",
    body: `All software, source code, APIs, databases (excluding customer-provided data), documentation, logos, trademarks, user interface designs and proprietary technology remain the exclusive property of Quantum Ripple LTD.

Schools receive a limited, non-exclusive, non-transferable licence to use the platform during an active subscription.`
  },

  {
    title: "7. Subscription and Billing",
    body: `The platform is provided as Software as a Service (SaaS).

Access depends upon an active subscription maintained by the School.

Failure to pay subscription fees may result in suspension or restricted access until outstanding balances are settled.`
  },

  {
    title: "8. Service Availability",
    body: `We strive to provide a secure and reliable service.

However, uninterrupted availability cannot be guaranteed.

Scheduled maintenance, emergency maintenance, software updates, internet outages, third-party service interruptions or circumstances beyond our control may temporarily affect service availability.`
  },

  {
    title: "9. Data Backups",
    body: `Quantum Ripple performs routine backups to support disaster recovery.

Schools are encouraged to maintain independent copies of critical institutional records where appropriate.`
  },

  {
    title: "10. Suspension and Termination",
    body: `Quantum Ripple may suspend or terminate accounts where:

• These Terms are violated
• Fraudulent activity is detected
• Platform security is threatened
• Subscription obligations are not met
• Required by law

Schools may also request closure of their accounts subject to applicable contractual obligations.`
  },

  {
    title: "11. Limitation of Liability",
    body: `To the fullest extent permitted by applicable law, Quantum Ripple LTD shall not be liable for:

• Decisions made using reports generated by the platform
• Incorrect information entered by users
• Internet outages
• Third-party service failures
• Force majeure events
• Indirect, incidental, special or consequential damages
• Loss of profits, goodwill or educational opportunities resulting from misuse of the platform`
  },

  {
    title: "12. Indemnification",
    body: `Schools agree to indemnify and hold Quantum Ripple harmless against claims arising from:

• Unlawful use of the platform
• Failure to obtain required parental consent
• Unauthorized disclosure of login credentials
• Incorrect information uploaded by the School
• Violations of applicable law by the School or its users`
  },

  {
    title: "13. Force Majeure",
    body: `Quantum Ripple shall not be responsible for delays or service interruptions caused by events beyond reasonable control, including natural disasters, cyberattacks, civil unrest, strikes, telecommunications failures or government actions.`
  },

  {
    title: "14. Governing Law",
    body: `These Terms are governed by the laws of the Republic of Kenya.

Any disputes shall first be addressed through good-faith negotiations before being referred to the competent courts of Kenya or another mutually agreed dispute resolution mechanism.`
  },

  {
    title: "15. Changes to these Terms",
    body: `We may update these Terms from time to time.

Material changes will be communicated through the platform or other appropriate communication channels.

Continued use of the platform after such changes constitutes acceptance of the updated Terms.`
  },

  {
    title: "16. Contact Information",
    body: `Quantum Ripple LTD

Email:
info@quantumripple.co.ke


Website:
https://www.quantumripple.co.ke

For questions regarding these Terms of Use, please contact us using the details above.`
  }
]
</script>

<template>
  <div class="min-h-screen bg-slate-100 px-4 py-8 text-slate-800">
    <div class="mx-auto flex max-w-5xl flex-col gap-6">
      <div class="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
        <div class="flex flex-wrap items-center justify-between gap-4">
          <div>
            <div class="space-y-2">
                <p class="text-sm font-semibold uppercase tracking-[0.3em] text-blue-600">
                  Terms of Use
                </p>

                <div class="flex flex-wrap gap-4 text-sm text-slate-500">
                  <span><strong>Effective:</strong> July 30, 2026</span>
                  <span><strong>Last Updated:</strong> August 10, 2026</span>
                </div>
              </div>
            <h1 class="mt-2 text-3xl font-semibold text-slate-900">Terms governing your use of the platform</h1>
            <p class="mt-3 max-w-2xl text-sm leading-6 text-slate-600">
              These terms explain how you may use the Quantum Ripple School Management Platform and what responsibilities apply while using it.
            </p>
          </div>
          <router-link
            to="/login"
            class="inline-flex items-center rounded-full border border-slate-200 px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-blue-500 hover:text-blue-600"
          >
            Back to login
          </router-link>
        </div>
      </div>

      <div class="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
        <div class="rounded-2xl bg-slate-50 p-6">
          <p class="text-sm leading-7 text-slate-700">
            By accessing the platform, you agree to comply with these Terms of Use and all applicable laws, regulations, and school policies. These terms supplement the Privacy Policy and apply to all users, including students, parents, teachers, administrators, and support personnel.
          </p>
        </div>

        <div class="mt-8 space-y-6">
          <div
            v-for="clause in clauses"
            :key="clause.title"
            class="rounded-2xl border border-slate-200 p-5"
          >
            <h2 class="text-lg font-semibold text-slate-900">{{ clause.title }}</h2>
            <p class="mt-2 text-sm leading-7 text-slate-600">{{ clause.body }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
